// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PreeceTechnology.Data;

#nullable disable

namespace PreeceTechnology.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20230623201918_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PreeceTechnology.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NeedStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ultra Router",
                            InStock = 200,
                            Name = "Speed Router",
                            NeedStock = 800
                        },
                        new
                        {
                            Id = 2,
                            Description = "Multi-tool",
                            InStock = 600,
                            Name = "Multi-tool",
                            NeedStock = 400
                        },
                        new
                        {
                            Id = 3,
                            Description = "4K Monitor",
                            InStock = 100,
                            Name = "24 4K monitor",
                            NeedStock = 1200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
