// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PreeceTechnology.Data;

#nullable disable

namespace PreeceTechnology.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20230623214137_NewDepartment")]
    partial class NewDepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PreeceTechnology.Models.Department", b =>
                {
                    b.Property<string>("DepartmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = "RR",
                            DepartmentName = "Routers"
                        },
                        new
                        {
                            DepartmentId = "DM",
                            DepartmentName = "Displays / Monitors"
                        },
                        new
                        {
                            DepartmentId = "AC",
                            DepartmentName = "Accessories"
                        },
                        new
                        {
                            DepartmentId = "PT",
                            DepartmentName = "PC Towers"
                        },
                        new
                        {
                            DepartmentId = "SS",
                            DepartmentName = "Software"
                        },
                        new
                        {
                            DepartmentId = "OA",
                            DepartmentName = "All-in-one Desktops"
                        });
                });

            modelBuilder.Entity("PreeceTechnology.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NeedStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = "RR",
                            Description = "Ultra Router",
                            InStock = 200,
                            Name = "Speed Router",
                            NeedStock = 800
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = "AC",
                            Description = "Multi-tool",
                            InStock = 600,
                            Name = "Multi-tool",
                            NeedStock = 400
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = "DM",
                            Description = "4K Monitor",
                            InStock = 100,
                            Name = "24 4K monitor",
                            NeedStock = 1200
                        });
                });

            modelBuilder.Entity("PreeceTechnology.Models.Inventory", b =>
                {
                    b.HasOne("PreeceTechnology.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
